#ifndef LIBOPENVPN_GLOBAL_H
#define LIBOPENVPN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBOPENVPN_LIBRARY)
#  define LIBOPENVPN_EXPORT Q_DECL_EXPORT
#else
#  define LIBOPENVPN_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBOPENVPN_GLOBAL_H
